name: Production

on:
  workflow_dispatch:

env:
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: docker-compose restart
        uses: appleboy/ssh-action@master
        with:
          host: 101.35.215.228
          username: ubuntu
          key: ${{ secrets.PROD_SERVER_KEY }}
          port: 22
          script: |
            export TARGET_JAR=/apps/data/duanju-build/duanju-api@${{env.IMAGE_VERSION}}/target/duanju.jar
            cd /apps/srv && make restart-backend